# Generated by Django 4.2 on 2023-04-10 17:12

from django.db import migrations, models
import portfolio.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(default='', upload_to=portfolio.utils.upload_picture)),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
